language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install flask spotipy pandas numpy scikit-learn pytest
# command to run tests

script:
  - py.test -v --color=yes --exitfirst --showlocals --durations=5

after_success:
  - python train.py



