language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install flask spotipy pandas numpy scikit-learn
# command to run tests
script:
  - python train.py



